import { EQUIPMENT_SLOTS, EQUIPMENT_WEIGHTS } from "../data/equipment";
import type { EquipmentSlot, WeaponId } from "../data/types";
import { WEAPONS } from "../data/weapons";
import { Rng } from "./Rng";

export type Reward = { kind: "gold"; amount: number } | { kind: "weapon"; weapon: WeaponId } | { kind: "skill" } | { kind: "fragment"; slot: EquipmentSlot } | { kind: "mystery" };
export class RewardSystem {
  constructor(private rng: Rng) {}
  rewards(): Reward[] { const pool = [{ value: "gold", weight: 30 }, { value: "weapon", weight: 10 }, { value: "skill", weight: 30 }, { value: "fragment", weight: 5 }, { value: "mystery", weight: 5 }]; const count = this.rng.int(2, 4), result: Reward[] = []; while (result.length < count && pool.length) { const type = this.rng.weighted(pool); pool.splice(pool.findIndex((item) => item.value === type), 1); if (type === "gold") result.push({ kind: "gold", amount: this.rng.int(10, 50) }); if (type === "weapon") result.push({ kind: "weapon", weapon: this.rng.pick(Object.keys(WEAPONS) as WeaponId[]) }); if (type === "skill") result.push({ kind: "skill" }); if (type === "fragment") result.push({ kind: "fragment", slot: this.rng.weighted(EQUIPMENT_SLOTS.map((slot) => ({ value: slot, weight: EQUIPMENT_WEIGHTS[slot] }))) }); if (type === "mystery") result.push({ kind: "mystery" }); } return result; }
  skills(): { name: string; stat: "crit" | "attack" | "attackSpeed" | "maxHp"; value: number; color: number }[] { const values = [{ value: .2, color: 0xe5e5df, name: "白" }, { value: .3, color: 0x5594d9, name: "蓝" }, { value: .4, color: 0x9b64ca, name: "紫" }, { value: .6, color: 0xd8b140, name: "金" }]; const options: { name: string; stat: "crit" | "attack" | "attackSpeed" | "maxHp"; value: number; color: number }[] = []; const stats: { stat: "crit" | "attack" | "attackSpeed" | "maxHp"; label: string }[] = [{ stat: "crit", label: "暴击率" }, { stat: "attack", label: "攻击" }, { stat: "attackSpeed", label: "攻速" }, { stat: "maxHp", label: "生命" }]; while (options.length < 3) { const rarity = this.rng.weighted([{ value: values[0], weight: 40 }, { value: values[1], weight: 30 }, { value: values[2], weight: 20 }, { value: values[3], weight: 10 }]); const stat = this.rng.pick(stats); if (!options.some((option) => option.stat === stat.stat)) options.push({ name: `${rarity.name}·${stat.label} +${rarity.value * 100}%`, stat: stat.stat, value: rarity.value, color: rarity.color }); } return options; }
}
